### ISSUE TITLE
Undefined variable data in DB.php 

### ISSUE THREAD

**Issue by BruurTycho** [howCodeORG/Social-Network#2]
Getting this error in my PHP logs:
[Mon Jan 16 16:42:43.787722 2017] [:error] [pid X] [client X] PHP Notice:  Undefined variable: data in /<loc to docs>/classes/DB.php on line 16, referer: <my domain>/login.php

My PHP is this:
`<?php 

class DB {
	private static function connect() {
		
		$pdo = new PDO('mysql:host=X;dbname=gimmesne_SN;charset=utf8', 'gimmesne_sn', 'X');
        $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);	
		return $pdo;
	}
	public static function query($query, $params = array()) {
		$statement = self::connect()->prepare($query);
		$statement->execute($params);
		
		if (explode(' ', $query)[0] == 'SELECT') {	
		$date = $statement->fetchAll();
		return $data;
		}
	}
}

?>`

**Comment by howCodeORG** [comment]
You created a variable called `$date`, change it to `$data`.

**Comment by BruurTycho** [comment]
Oh your right! Haha.
